import React, { FunctionComponent, PropsWithChildren } from 'react';
import Head from 'next/head';
import Header from '../header';

type Props = {
  pageTitle: string;
};

const BaseLayout: FunctionComponent<PropsWithChildren<Props>> = ({
  children,
  pageTitle,
}) => {
  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="m-auto flex h-full min-h-screen max-w-[340px] flex-col items-center justify-center border border-blue-500 sm:max-w-[580px]">
        <Header pageTitle={pageTitle} />
        <div className="w-full">{children}</div>
      </main>
    </>
  );
};

export default BaseLayout;
